### ISSUE TITLE
push to channels

### ISSUE THREAD

**Issue by HOSTED-POWER** [konstantin-kelemen/icinga2-pushbullet-notifications#2]
Hi,

First of all, thank you so much, this is exactly what we needed!

However wouldn't it be easier to push to channels? This way you could have just one pushbullet account defined in icinga and anyone that requires access can simply subscribe to the channel instead of being defined in the config :) 

Also it would allow to send to as many accounts/devices you want.

In any case I modified the scripts code slightly and it works perfectly for or setup, e.g.:

curl https://api.pushbullet.com/api/pushes -u $APIKEY: -d channel_tag=$DEVID -d type=note --data-urlencode "title=$TITLE" --data-urlencode "body=$BODY" -X POST

**Comment by konstantin-kelemen** [comment]
Hi @HOSTED-POWER,

first of all, thanks for your interest and feedback!

I really hadn't enough experience using Pushbullet with all its reach features, since I switched to Telegram notifications after just a few days since publishing this code.

Anyway, thanks for your helpful suggestion, hope others will find it really useful!
